version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: nitin-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nitin_billing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - nitin-network

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: nitin-backend
    environment:
      - DEBUG=False
      - DB_ENGINE=postgresql
      - DB_NAME=nitin_billing
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=*
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - nitin-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nitin-frontend
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    ports:
      - "80:3000"
    networks:
      - nitin-network

networks:
  nitin-network:
    driver: bridge

volumes:
  postgres_data:
