# Generated by Django 5.2.12 on 2026-04-07 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('room_type', models.CharField(choices=[('NORMAL', 'Normal'), ('GENERAL_WARD', 'General Ward'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=20)),
                ('floor', models.IntegerField(default=1)),
                ('bed_count', models.IntegerField(default=1)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('ailment', models.CharField(blank=True, default='', max_length=255)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('is_discharged', models.BooleanField(default=False)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='hospital.doctor')),
                ('assigned_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='hospital.room')),
            ],
        ),
    ]
