# Generated by Django 5.2.12 on 2026-04-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_ambulancevehicle_bloodstock_pharmacyitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='category',
            field=models.CharField(choices=[('PATHOLOGY', 'Pathology (Blood/Urine)'), ('RADIOLOGY', 'Radiology (X-Ray/MRI/CT)'), ('CARDIOLOGY', 'Cardiology (ECG)'), ('OTHER', 'Other')], default='PATHOLOGY', max_length=20),
        ),
        migrations.AddField(
            model_name='labtest',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='labtest',
            name='priority',
            field=models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'STAT (Emergency)')], default='ROUTINE', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='blood_group',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
