# Generated by Django 5.2.12 on 2026-04-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_labtest_category_labtest_cost_labtest_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancedispatch',
            name='estimated_eta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ambulancevehicle',
            name='has_defibrillator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ambulancevehicle',
            name='has_o2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ambulancevehicle',
            name='has_ventilator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ambulancevehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('BLS', 'Basic Life Support (BLS)'), ('ALS', 'Advanced Life Support (ALS / Mobile ICU)'), ('PTS', 'Patient Transport Service (PTS)')], default='BLS', max_length=20),
        ),
    ]
